image:  rlouapre/centos6-ml
script:
  - /etc/rc.d/init.d/MarkLogic start
  - sleep 10
  - curl localhost:8001 -v
  - yum -y install nodejs npm
  - ./.drone/npm install -g gulp
  - ./.drone/npm install
  - ./.drone/gulp ml:init
