image:  rlouapre/centos6-ml7
script:
  - /etc/rc.d/init.d/MarkLogic start
  - cd ./.drone/
  - npm install -g -q gulp
  - npm install -q
  - gulp ml:init
  - curl localhost:8001 --anyauth --user admin:admin -v
